### 1. Sign up a new user 

### 📌 Copy the token from above response JSON and paste it below

### 2. Get current user
GET http://localhost:5001/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODcyOGI3ZDJhMmI1MDI5OWFjMDI3YTUiLCJpYXQiOjE3NTIzMzcyNzcsImV4cCI6MTc1Mjk0MjA3N30.lgfeAUCpHENuZLg30sSfzq9n2pjvTYP5UipdAXs-1og

### 3. Update user name
PUT http://localhost:5001/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODcyOGI3ZDJhMmI1MDI5OWFjMDI3YTUiLCJpYXQiOjE3NTIzMzcyNzcsImV4cCI6MTc1Mjk0MjA3N30.lgfeAUCpHENuZLg30sSfzq9n2pjvTYP5UipdAXs-1og

{
  "name": "Updated Name"
}
